### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by renkin4** [CybernetHacker14/Ghost-Engine#3]
Hey IDK what am I doing wrong But I am unable to compile follow the steps shown in read me 
Some shader files are missing 
![image](https://user-images.githubusercontent.com/21073503/119511119-b1310c80-bda4-11eb-90b6-7965bc73c52e.png)

**Comment by CybernetHacker14** [comment]
The README hasn't been updated. Thanks for bringing this to my notice. Create the project by executing `Setup.bat` file, in `scripts` folder.
